name: cronjob
env:
    GIT_OAUTH_TOKEN_XFU: ${{ secrets.GIT_OAUTH_TOKEN_XFU }}
    BOTTOKEN: ${{ secrets.BOTTOKEN }}

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install requests
    - name: Run
      run: python3 sync.py
